swagger: '2.0'
info:
  description: This document describe the API for transactions App. A financial transactions tracking.
  version: 1.0.0
  title: Swagger Transactions App
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: renatto.martins@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: transações.io
basePath: /v1
tags:
  - name: base
    description: Initial endpoints
  - name: transactions
    description: All your financial transaction tracking
  - name: users
    description: Operations about user
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: API Entry point
      tags:
        - base
      operationId: entryPoint
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/WelcomeResponsePayload'
  /health:
    get:
      summary: Healthcheck endpoint
      tags:
        - base
      operationId: health
      produces:
        - text/plain
      responses:
        '200':
          description: Ok
  /users:
    post:
      summary: Sign up new users
      description: ''
      tags:
        - users
      operationId: addUser
      parameters:
        - in: body
          name: user
          description: User object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/UserRequestPayload'
      responses:
        '201':
          description: Created
          headers:
            Location:
              type: string
              description: The location of the new User
          schema:
            $ref: '#/definitions/User'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/500CodeResponsePayload'
  '/transactions':
    get:
      summary: Get a list of transactions
      tags:
        - transactions
      operationId: getTransactions
      responses:
        '200':
          description: Ok
    post:
      tags:
        - transactions
      summary: Add a new transaction
      description: ''
      operationId: addTransaction
      parameters:
        - in: body
          name: body
          description: Transaction object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          headers:
            X-Total-Count:
              type: integer
              format: int32
              description: Number of transactions in response
        '405':
          description: Invalid input
  '/transactions/{transactionId}':
    get:
      tags:
        - transactions
      summary: Get a transaction
      operationId: getTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
    put:
      tags:
        - transactions
      summary: Update an existing transaction
      operationId: updateTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
        '405':
          description: Validation exception
    patch:
      tags:
        - transactions
      summary: Update parcially an existing transaction
      operationId: patchTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
        '405':
          description: Validation exception
    delete:
      tags:
        - transactions
      summary: Delete an existing transaction
      operationId: deleteTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
definitions:
  WelcomeResponsePayload:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
      version:
        type: string
        example: 1.0.0
      resources:
        $ref: '#/definitions/WelcomeResponseResources'
  WelcomeResponseResources:
    type: object
    properties:
      transaction_url:
        type: string
        example: http://api.transações.io/transactions
      user_url:
        type: string
        example: http://api.transações.io/users
  500CodeResponsePayload:
    type: object
    properties:
      code:
        type: integer
        example: 500
      message:
        type: string
        example: 'Internal Server Error'
  UserRequestPayload:
    type: object
    required:
      - email
      - password
      - passwordVerification
    properties:
      email:
        type: string
        example: renato@transactions.app
      password:
        type: string
        example: 12345
      passwordVerification:
        type: string
        example: 12345
        description: passwordVerification and password fields must be equal.
  User:
    type: object
    required:
      - email
      - password
    properties:
      id:
        type: integer
        format: int64
        example: 1
      email:
        type: string
        example: renato@transactions.app
      created:
        type: string
        example: '2021-07-16T08:14:34.606Z'
      modified:
        type: string
        example: '2021-07-16T08:14:34.606Z'
  Transaction:
    type: object
    required:
      - description
      - amount
      - date
      - is_income
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
      amount:
        type: number
        format: double
      date:
        type: string
      notes:
        type: string
      is_income:
        type: boolean
externalDocs:
  description: Find out more about Transactions App
  url: 'https://transações.io'
