swagger: '2.0'
info:
  description: This document describe the API for transactions App. A financial transactions tracking.
  version: 1.0.0
  title: Swagger Transactions App
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: renatto.martins@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: transações.io
basePath: /v1
tags:
  - name: base
    description: Initial endpoints
  - name: accounts
    description: All your financial accounts
  - name: transactions
    description: All your financial transaction tracking
  - name: users
    description: Operations about user
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: API Entry point
      tags:
        - base
      operationId: entryPoint
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/WelcomeResponsePayload'
  /health:
    get:
      summary: Healthcheck endpoint
      tags:
        - base
      operationId: health
      produces:
        - text/plain
      responses:
        '200':
          description: Ok
  /users:
    post:
      summary: Sign up new users
      description: ''
      tags:
        - users
      operationId: addUser
      parameters:
        - in: body
          name: user
          description: User object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/UserRequestPayload'
      responses:
        '201':
          description: Created
          headers:
            Location:
              type: string
              description: The location of the new User
          schema:
            $ref: '#/definitions/User'
  /accounts:
    get:
      summary: Get a list of accounts
      tags:
        - accounts
      operationId: getAccounts
      responses:
        '200':
          description: Ok
    post:
      tags:
        - accounts
      summary: Add a new financial account
      description: ''
      operationId: addAccount
      parameters:
        - in: body
          name: body
          description: Account object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: Ok
          headers:
            X-Total-Count:
              type: integer
              format: int32
              description: Number of accounts in response
        '405':
          description: Invalid input
  '/accounts/{accountId}':
    get:
      tags:
        - accounts
      summary: Get a financial account
      operationId: getAccount
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
    put:
      tags:
        - accounts
      summary: Update an existing financial account
      operationId: updateAccount
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Account object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
        '405':
          description: Validation exception
    patch:
      tags:
        - accounts
      summary: Update parcially an existing financial account
      operationId: patchAccount
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Account object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
        '405':
          description: Validation exception
    delete:
      tags:
        - accounts
      summary: Delete an existing financial account
      operationId: deleteAccount
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  '/accounts/{accountId}/transactions':
    get:
      summary: Get a list of transactions
      tags:
        - transactions
      operationId: getTransactions
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Ok
    post:
      tags:
        - transactions
      summary: Add a new transaction
      description: ''
      operationId: addTransaction
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          headers:
            X-Total-Count:
              type: integer
              format: int32
              description: Number of transactions in response
        '405':
          description: Invalid input
  '/accounts/{accountId}/transactions/{transactionId}':
    get:
      tags:
        - transactions
      summary: Get a transaction
      operationId: getTransaction
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
    put:
      tags:
        - transactions
      summary: Update an existing transaction
      operationId: updateTransaction
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
        '405':
          description: Validation exception
    patch:
      tags:
        - transactions
      summary: Update parcially an existing transaction
      operationId: patchTransaction
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Transaction object that needs to be uptaded
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
        '405':
          description: Validation exception
    delete:
      tags:
        - transactions
      summary: Delete an existing transaction
      operationId: deleteTransaction
      parameters:
        - name: accountId
          in: path
          description: ID of account to which the transaction belongs
          required: true
          type: integer
          format: int64
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: No content
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
definitions:
  WelcomeResponsePayload:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
      version:
        type: string
        example: 1.0.0
      resources:
        $ref: '#/definitions/WelcomeResponseResources'
  WelcomeResponseResources:
    type: object
    properties:
      account_url:
        type: string
        example: http://api.transações.io/accounts
      transaction_url:
        type: string
        example: http://api.transações.io/transactions
      user_url:
        type: string
        example: http://api.transações.io/users
  UserRequestPayload:
    type: object
    required:
      - email
      - password
      - passwordVerification
    properties:
      email:
        type: string
        example: renato@transactions.app
      password:
        type: string
        example: 12345
      passwordVerification:
        type: string
        example: 12345
        description: passwordVerification and password fields must be equal.
  User:
    type: object
    required:
      - email
      - password
    properties:
      id:
        type: integer
        format: int64
        example: 1
      email:
        type: string
        example: renato@transactions.app
      created:
        type: string
        example: '2021-07-16 08:14:34'
      modified:
        type: string
        example: '2021-07-16 08:14:34'
  Account:
    type: object
    required:
      - name
      - icon
      - type
      - initial_amount
      - activated
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: Banco Inter
      icon:
        type: string
        example: icon-banco-inter
      type:
        type: string
        enum:
          - CheckingAccount
          - SavingAccount
          - InvestmentAccount
          - CreditCard
          - Money
          - Other
      initial_amount:
        type: number
        format: double
      activated:
        type: boolean
        example: true
  Transaction:
    type: object
    required:
      - description
      - amount
      - date
      - is_income
      - is_transfer
      - account_id
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
      amount:
        type: number
        format: double
      date:
        type: string
      notes:
        type: string
      is_income:
        type: boolean
      is_transfer:
        type: boolean
      account_id:
        type: integer
        format: int64
      account:
        $ref: '#/definitions/Account'
      related_transfer_id:
        type: string
externalDocs:
  description: Find out more about Transactions App
  url: 'https://transações.io'
